apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv
spec:
  containers:
  - image: mysql
    name: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: test
      - name: MYSQL_DATABASE
        value: test_dn
      - name: MYSQL_USER
        value: root
      - name: MYSQL_PASSWORD
        value: root
  volumes:
  - name: mysql-data
    persistentVolumeClaim:
      claimName: pvc
